// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  userId: __t.u64().name("user_id"),
  username: __t.string(),
  joinedAt: __t.timestamp().name("joined_at"),
  seat: __t.u8(),
  color: __t.string(),
  armiesToPlace: __t.u32().name("armies_to_place"),
  cardCount: __t.u32().name("card_count"),
  eliminated: __t.bool(),
  forfeited: __t.bool(),
});
