// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Battle,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  creatorId: __t.u64().name("creator_id"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  startedAt: __t.option(__t.timestamp()).name("started_at"),
  finishedAt: __t.option(__t.timestamp()).name("finished_at"),
  playerCount: __t.u8().name("player_count"),
  currentSeat: __t.u8().name("current_seat"),
  phase: __t.string(),
  turnNumber: __t.u32().name("turn_number"),
  reinforcements: __t.u32(),
  setsTraded: __t.u32().name("sets_traded"),
  conqueredThisTurn: __t.bool().name("conquered_this_turn"),
  cardBonusTaken: __t.bool().name("card_bonus_taken"),
  forcedTrade: __t.bool().name("forced_trade"),
  occupyFrom: __t.u8().name("occupy_from"),
  occupyTo: __t.u8().name("occupy_to"),
  get lastBattle() {
    return __t.option(Battle).name("last_battle");
  },
  winnerId: __t.option(__t.u64()).name("winner_id"),
  winnerName: __t.string().name("winner_name"),
});
