// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AttackReducer from "../attack_reducer";
import BeginGameReducer from "../begin_game_reducer";
import CreateGameReducer from "../create_game_reducer";
import EndAttackReducer from "../end_attack_reducer";
import EndTurnReducer from "../end_turn_reducer";
import FinishReinforceReducer from "../finish_reinforce_reducer";
import ForfeitReducer from "../forfeit_reducer";
import FortifyReducer from "../fortify_reducer";
import JoinGameReducer from "../join_game_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import LoginReducer from "../login_reducer";
import LogoutReducer from "../logout_reducer";
import OccupyReducer from "../occupy_reducer";
import PlaceArmiesReducer from "../place_armies_reducer";
import RegisterReducer from "../register_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetupPlaceReducer from "../setup_place_reducer";
import TradeCardsReducer from "../trade_cards_reducer";

export type AttackParams = __Infer<typeof AttackReducer>;
export type BeginGameParams = __Infer<typeof BeginGameReducer>;
export type CreateGameParams = __Infer<typeof CreateGameReducer>;
export type EndAttackParams = __Infer<typeof EndAttackReducer>;
export type EndTurnParams = __Infer<typeof EndTurnReducer>;
export type FinishReinforceParams = __Infer<typeof FinishReinforceReducer>;
export type ForfeitParams = __Infer<typeof ForfeitReducer>;
export type FortifyParams = __Infer<typeof FortifyReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type OccupyParams = __Infer<typeof OccupyReducer>;
export type PlaceArmiesParams = __Infer<typeof PlaceArmiesReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetupPlaceParams = __Infer<typeof SetupPlaceReducer>;
export type TradeCardsParams = __Infer<typeof TradeCardsReducer>;

